apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "google-checker"
        metrics_path: /metrics
        static_configs:
          - targets: ["google-checker-service:80"]