# Service
apiVersion: v1
kind: Service
metadata:
  name: google-checker-service
spec:
  selector:
    app: google-checker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort